### ISSUE TITLE
not working (unfortunately)

### ISSUE THREAD

**Issue by wkerzendorf** [mjkaufer/Stats#4]
Hi,

This seems like a useful tool - unfortunately it doesn't work. I tried with my handle @wkerzendorf but it just sits there. 

Making this functional would be very nice. 

Thanks for making it open!!

**Comment by mjkaufer** [comment]
Hi,

I'm on mobile right now so I can't really debug, but just to check: you didn't add the "@" when entering your username, right? I'll look into this a bit more when I get access to a desktop.

**Comment by wkerzendorf** [comment]
Nope didn't add the @ - good luck

**Comment by mjkaufer** [comment]
Fixed!
